// Auto-generated by scripts/build/generate-provider-index.mjs.
// Do not edit by hand; set NEXT_PUBLIC_ENABLED_PROVIDERS and rerun the generator.

import type { RegistryEntry } from "./shared.ts";

import { adapta_webProvider } from "./registry/adapta-web/index.ts";
import { agentrouterProvider } from "./registry/agentrouter/index.ts";
import { agyProvider } from "./registry/agy/index.ts";
import { ai21Provider } from "./registry/ai21/index.ts";
import { aimlapiProvider } from "./registry/aimlapi/index.ts";
import { alibabaProvider } from "./registry/alibaba/index.ts";
import { alibaba_cnProvider } from "./registry/alibaba/cn/index.ts";
import { anthropicProvider } from "./registry/anthropic/index.ts";
import { antigravityProvider } from "./registry/antigravity/index.ts";
import { api_airforceProvider } from "./registry/api-airforce/index.ts";
import { auggieProvider } from "./registry/auggie/index.ts";
import { baiProvider } from "./registry/bai/index.ts";
import { baichuanProvider } from "./registry/baichuan/index.ts";
import { baiduProvider } from "./registry/baidu/index.ts";
import { bailian_coding_planProvider } from "./registry/bailian-coding-plan/index.ts";
import { basetenProvider } from "./registry/baseten/index.ts";
import { bazaarlinkProvider } from "./registry/bazaarlink/index.ts";
import { bedrockProvider } from "./registry/bedrock/index.ts";
import { blackboxProvider } from "./registry/blackbox/index.ts";
import { blackbox_webProvider } from "./registry/blackbox/web/index.ts";
import { bluesmindsProvider } from "./registry/bluesminds/index.ts";
import { byteplusProvider } from "./registry/byteplus/index.ts";
import { bytezProvider } from "./registry/bytez/index.ts";
import { cerebrasProvider } from "./registry/cerebras/index.ts";
import { charmHyperProvider } from "./registry/charm-hyper/index.ts";
import { chatgpt_webProvider } from "./registry/chatgpt-web/index.ts";
import { chipotleProvider } from "./registry/chipotle/index.ts";
import { chutesProvider } from "./registry/chutes/index.ts";
import { claudeProvider } from "./registry/claude/index.ts";
import { claude_webProvider } from "./registry/claude/web/index.ts";
import { clineProvider } from "./registry/cline/index.ts";
import { clinepassProvider } from "./registry/clinepass/index.ts";
import { cloudflare_aiProvider } from "./registry/cloudflare-ai/index.ts";
import { codebuddy_cnProvider } from "./registry/codebuddy-cn/index.ts";
import { codestralProvider } from "./registry/codestral/index.ts";
import { codexProvider } from "./registry/codex/index.ts";
import { cohereProvider } from "./registry/cohere/index.ts";
import { command_codeProvider } from "./registry/command-code/index.ts";
import { copilot_m365_webProvider } from "./registry/copilot-m365-web/index.ts";
import { copilot_webProvider } from "./registry/copilot-web/index.ts";
import { cozeProvider } from "./registry/coze/index.ts";
import { crofProvider } from "./registry/crof/index.ts";
import { cursorProvider } from "./registry/cursor/index.ts";
import { databricksProvider } from "./registry/databricks/index.ts";
import { deepinfraProvider } from "./registry/deepinfra/index.ts";
import { deepseekProvider } from "./registry/deepseek/index.ts";
import { deepseek_webProvider } from "./registry/deepseek/web/index.ts";
import { devin_cliProvider } from "./registry/devin-cli/index.ts";
import { dgridProvider } from "./registry/dgrid/index.ts";
import { difyProvider } from "./registry/dify/index.ts";
import { digitaloceanProvider } from "./registry/digitalocean/index.ts";
import { ditProvider } from "./registry/dit/index.ts";
import { doubaoProvider } from "./registry/doubao/index.ts";
import { doubao_webProvider } from "./registry/doubao/web/index.ts";
import { duckduckgo_webProvider } from "./registry/duckduckgo-web/index.ts";
import { factoryProvider } from "./registry/factory/index.ts";
import { featherless_aiProvider } from "./registry/featherless-ai/index.ts";
import { fireworksProvider } from "./registry/fireworks/index.ts";
import { freeaiapikeyProvider } from "./registry/freeaiapikey/index.ts";
import { freemodel_devProvider } from "./registry/freemodel-dev/index.ts";
import { friendliaiProvider } from "./registry/friendliai/index.ts";
import { galadrielProvider } from "./registry/galadriel/index.ts";
import { geminiProvider } from "./registry/gemini/index.ts";
import { gemini_webProvider } from "./registry/gemini/web/index.ts";
import { gigachatProvider } from "./registry/gigachat/index.ts";
import { githubProvider } from "./registry/github/index.ts";
import { github_modelsProvider } from "./registry/github/models/index.ts";
import { gitlab_duoProvider } from "./registry/gitlab-duo/index.ts";
import { gitlawbProvider } from "./registry/gitlawb/index.ts";
import { gitlawb_gmiProvider } from "./registry/gitlawb/gmi/index.ts";
import { glhfProvider } from "./registry/glhf/index.ts";
import { glmProvider } from "./registry/glm/index.ts";
import { glm_cnProvider } from "./registry/glm/cn/index.ts";
import { glmtProvider } from "./registry/glm/t/index.ts";
import { grok_cliProvider } from "./registry/grok-cli/index.ts";
import { grok_webProvider } from "./registry/grok-web/index.ts";
import { groqProvider } from "./registry/groq/index.ts";
import { hackclubProvider } from "./registry/hackclub/index.ts";
import { haiperProvider } from "./registry/haiper/index.ts";
import { hcnsecProvider } from "./registry/hcnsec/index.ts";
import { herokuProvider } from "./registry/heroku/index.ts";
import { huggingchatProvider } from "./registry/huggingchat/index.ts";
import { huggingfaceProvider } from "./registry/huggingface/index.ts";
import { hyperbolicProvider } from "./registry/hyperbolic/index.ts";
import { ideogramProvider } from "./registry/ideogram/index.ts";
import { iflytekProvider } from "./registry/iflytek/index.ts";
import { inclusionaiProvider } from "./registry/inclusionai/index.ts";
import { inference_netProvider } from "./registry/inference-net/index.ts";
import { inner_aiProvider } from "./registry/inner-ai/index.ts";
import { kenariProvider } from "./registry/kenari/index.ts";
import { kieProvider } from "./registry/kie/index.ts";
import { kilo_gatewayProvider } from "./registry/kilo-gateway/index.ts";
import { kilocodeProvider } from "./registry/kilocode/index.ts";
import { kimiProvider } from "./registry/kimi/index.ts";
import { kimi_codingProvider } from "./registry/kimi/coding/index.ts";
import { kimi_coding_apikeyProvider } from "./registry/kimi/coding-apikey/index.ts";
import { kimi_webProvider } from "./registry/kimi/web/index.ts";
import { kiroProvider } from "./registry/kiro/index.ts";
import { klusterProvider } from "./registry/kluster/index.ts";
import { lambda_aiProvider } from "./registry/lambda-ai/index.ts";
import { leonardoProvider } from "./registry/leonardo/index.ts";
import { liquidProvider } from "./registry/liquid/index.ts";
import { llamagateProvider } from "./registry/llamagate/index.ts";
import { llm7Provider } from "./registry/llm7/index.ts";
import { longcatProvider } from "./registry/longcat/index.ts";
import { maritalkProvider } from "./registry/maritalk/index.ts";
import { meta_llamaProvider } from "./registry/meta-llama/index.ts";
import { mimocodeProvider } from "./registry/mimocode/index.ts";
import { minimaxProvider } from "./registry/minimax/index.ts";
import { minimax_cnProvider } from "./registry/minimax/cn/index.ts";
import { mistralProvider } from "./registry/mistral/index.ts";
import { modalProvider } from "./registry/modal/index.ts";
import { modelscopeProvider } from "./registry/modelscope/index.ts";
import { monsterapiProvider } from "./registry/monsterapi/index.ts";
import { moonshotProvider } from "./registry/moonshot/index.ts";
import { morphProvider } from "./registry/morph/index.ts";
import { muse_spark_webProvider } from "./registry/muse-spark-web/index.ts";
import { nanogptProvider } from "./registry/nanogpt/index.ts";
import { nebiusProvider } from "./registry/nebius/index.ts";
import { nlpcloudProvider } from "./registry/nlpcloud/index.ts";
import { nous_researchProvider } from "./registry/nous-research/index.ts";
import { novitaProvider } from "./registry/novita/index.ts";
import { nscaleProvider } from "./registry/nscale/index.ts";
import { nubeProvider } from "./registry/nube/index.ts";
import { nvidiaProvider } from "./registry/nvidia/index.ts";
import { ollama_cloudProvider } from "./registry/ollama-cloud/index.ts";
import { openadapterProvider } from "./registry/openadapter/index.ts";
import { openaiProvider } from "./registry/openai/index.ts";
import { opencodeProvider } from "./registry/opencode/index.ts";
import { opencode_goProvider } from "./registry/opencode/go/index.ts";
import { opencode_zenProvider } from "./registry/opencode/zen/index.ts";
import { openrouterProvider } from "./registry/openrouter/index.ts";
import { orcarouterProvider } from "./registry/orcarouter/index.ts";
import { ovhcloudProvider } from "./registry/ovhcloud/index.ts";
import { perplexityProvider } from "./registry/perplexity/index.ts";
import { perplexity_webProvider } from "./registry/perplexity/web/index.ts";
import { pioneerProvider } from "./registry/pioneer/index.ts";
import { pollinationsProvider } from "./registry/pollinations/index.ts";
import { predibaseProvider } from "./registry/predibase/index.ts";
import { publicaiProvider } from "./registry/publicai/index.ts";
import { puterProvider } from "./registry/puter/index.ts";
import { qianfanProvider } from "./registry/qianfan/index.ts";
import { qiniuProvider } from "./registry/qiniu/index.ts";
import { qoderProvider } from "./registry/qoder/index.ts";
import { qwenProvider } from "./registry/qwen/index.ts";
import { qwen_webProvider } from "./registry/qwen/web/index.ts";
import { rekaProvider } from "./registry/reka/index.ts";
import { requestyProvider } from "./registry/requesty/index.ts";
import { sambanovaProvider } from "./registry/sambanova/index.ts";
import { scalewayProvider } from "./registry/scaleway/index.ts";
import { sensenovaProvider } from "./registry/sensenova/index.ts";
import { siliconflowProvider } from "./registry/siliconflow/index.ts";
import { snowflakeProvider } from "./registry/snowflake/index.ts";
import { sparkdeskProvider } from "./registry/sparkdesk/index.ts";
import { stepfunProvider } from "./registry/stepfun/index.ts";
import { sumopodProvider } from "./registry/sumopod/index.ts";
import { sunoProvider } from "./registry/suno/index.ts";
import { syntheticProvider } from "./registry/synthetic/index.ts";
import { t3_webProvider } from "./registry/t3-web/index.ts";
import { tencentProvider } from "./registry/tencent/index.ts";
import { theoldllmProvider } from "./registry/theoldllm/index.ts";
import { togetherProvider } from "./registry/together/index.ts";
import { tokenrouterProvider } from "./registry/tokenrouter/index.ts";
import { traeProvider } from "./registry/trae/index.ts";
import { udioProvider } from "./registry/udio/index.ts";
import { uncloseaiProvider } from "./registry/uncloseai/index.ts";
import { upstageProvider } from "./registry/upstage/index.ts";
import { v0_vercelProvider } from "./registry/v0-vercel/index.ts";
import { veniceProvider } from "./registry/venice/index.ts";
import { veoaifree_webProvider } from "./registry/veoaifree-web/index.ts";
import { vercel_ai_gatewayProvider } from "./registry/vercel-ai-gateway/index.ts";
import { vertexProvider } from "./registry/vertex/index.ts";
import { vertex_partnerProvider } from "./registry/vertex/partner/index.ts";
import { volcengineProvider } from "./registry/volcengine/index.ts";
import { waferProvider } from "./registry/wafer/index.ts";
import { wandbProvider } from "./registry/wandb/index.ts";
import { windsurfProvider } from "./registry/windsurf/index.ts";
import { x5labProvider } from "./registry/x5lab/index.ts";
import { xaiProvider } from "./registry/xai/index.ts";
import { xiaomi_mimoProvider } from "./registry/xiaomi-mimo/index.ts";
import { yiProvider } from "./registry/yi/index.ts";
import { yuanbao_webProvider } from "./registry/yuanbao-web/index.ts";
import { zaiProvider } from "./registry/zai/index.ts";
import { zed_hostedProvider } from "./registry/zed-hosted/index.ts";
import { zenmuxProvider } from "./registry/zenmux/index.ts";
import { zenmux_freeProvider } from "./registry/zenmux-free/index.ts";

export const REGISTRY: Record<string, RegistryEntry> = {
  "adapta-web": adapta_webProvider,
  "agentrouter": agentrouterProvider,
  "agy": agyProvider,
  "ai21": ai21Provider,
  "aimlapi": aimlapiProvider,
  "alibaba": alibabaProvider,
  "alibaba-cn": alibaba_cnProvider,
  "anthropic": anthropicProvider,
  "antigravity": antigravityProvider,
  "api-airforce": api_airforceProvider,
  "auggie": auggieProvider,
  "bai": baiProvider,
  "baichuan": baichuanProvider,
  "baidu": baiduProvider,
  "bailian-coding-plan": bailian_coding_planProvider,
  "baseten": basetenProvider,
  "bazaarlink": bazaarlinkProvider,
  "bedrock": bedrockProvider,
  "blackbox": blackboxProvider,
  "blackbox-web": blackbox_webProvider,
  "bluesminds": bluesmindsProvider,
  "byteplus": byteplusProvider,
  "bytez": bytezProvider,
  "cerebras": cerebrasProvider,
  "charm-hyper": charmHyperProvider,
  "chatgpt-web": chatgpt_webProvider,
  "chipotle": chipotleProvider,
  "chutes": chutesProvider,
  "claude": claudeProvider,
  "claude-web": claude_webProvider,
  "cline": clineProvider,
  "clinepass": clinepassProvider,
  "cloudflare-ai": cloudflare_aiProvider,
  "codebuddy-cn": codebuddy_cnProvider,
  "codestral": codestralProvider,
  "codex": codexProvider,
  "cohere": cohereProvider,
  "command-code": command_codeProvider,
  "copilot-m365-web": copilot_m365_webProvider,
  "copilot-web": copilot_webProvider,
  "coze": cozeProvider,
  "crof": crofProvider,
  "cursor": cursorProvider,
  "databricks": databricksProvider,
  "deepinfra": deepinfraProvider,
  "deepseek": deepseekProvider,
  "deepseek-web": deepseek_webProvider,
  "devin-cli": devin_cliProvider,
  "dgrid": dgridProvider,
  "dify": difyProvider,
  "digitalocean": digitaloceanProvider,
  "dit": ditProvider,
  "doubao": doubaoProvider,
  "doubao-web": doubao_webProvider,
  "duckduckgo-web": duckduckgo_webProvider,
  "factory": factoryProvider,
  "featherless-ai": featherless_aiProvider,
  "fireworks": fireworksProvider,
  "freeaiapikey": freeaiapikeyProvider,
  "freemodel-dev": freemodel_devProvider,
  "friendliai": friendliaiProvider,
  "galadriel": galadrielProvider,
  "gemini": geminiProvider,
  "gemini-web": gemini_webProvider,
  "gigachat": gigachatProvider,
  "github": githubProvider,
  "github-models": github_modelsProvider,
  "gitlab-duo": gitlab_duoProvider,
  "gitlawb": gitlawbProvider,
  "gitlawb-gmi": gitlawb_gmiProvider,
  "glhf": glhfProvider,
  "glm": glmProvider,
  "glm-cn": glm_cnProvider,
  "glmt": glmtProvider,
  "grok-cli": grok_cliProvider,
  "grok-web": grok_webProvider,
  "groq": groqProvider,
  "hackclub": hackclubProvider,
  "haiper": haiperProvider,
  "hcnsec": hcnsecProvider,
  "heroku": herokuProvider,
  "huggingchat": huggingchatProvider,
  "huggingface": huggingfaceProvider,
  "hyperbolic": hyperbolicProvider,
  "ideogram": ideogramProvider,
  "iflytek": iflytekProvider,
  "inclusionai": inclusionaiProvider,
  "inference-net": inference_netProvider,
  "inner-ai": inner_aiProvider,
  "kenari": kenariProvider,
  "kie": kieProvider,
  "kilo-gateway": kilo_gatewayProvider,
  "kilocode": kilocodeProvider,
  "kimi": kimiProvider,
  "kimi-coding": kimi_codingProvider,
  "kimi-coding-apikey": kimi_coding_apikeyProvider,
  "kimi-web": kimi_webProvider,
  "kiro": kiroProvider,
  "kluster": klusterProvider,
  "lambda-ai": lambda_aiProvider,
  "leonardo": leonardoProvider,
  "liquid": liquidProvider,
  "llamagate": llamagateProvider,
  "llm7": llm7Provider,
  "longcat": longcatProvider,
  "maritalk": maritalkProvider,
  "meta-llama": meta_llamaProvider,
  "mimocode": mimocodeProvider,
  "minimax": minimaxProvider,
  "minimax-cn": minimax_cnProvider,
  "mistral": mistralProvider,
  "modal": modalProvider,
  "modelscope": modelscopeProvider,
  "monsterapi": monsterapiProvider,
  "moonshot": moonshotProvider,
  "morph": morphProvider,
  "muse-spark-web": muse_spark_webProvider,
  "nanogpt": nanogptProvider,
  "nebius": nebiusProvider,
  "nlpcloud": nlpcloudProvider,
  "nous-research": nous_researchProvider,
  "novita": novitaProvider,
  "nscale": nscaleProvider,
  "nube": nubeProvider,
  "nvidia": nvidiaProvider,
  "ollama-cloud": ollama_cloudProvider,
  "openadapter": openadapterProvider,
  "openai": openaiProvider,
  "opencode": opencodeProvider,
  "opencode-go": opencode_goProvider,
  "opencode-zen": opencode_zenProvider,
  "openrouter": openrouterProvider,
  "orcarouter": orcarouterProvider,
  "ovhcloud": ovhcloudProvider,
  "perplexity": perplexityProvider,
  "perplexity-web": perplexity_webProvider,
  "pioneer": pioneerProvider,
  "pollinations": pollinationsProvider,
  "predibase": predibaseProvider,
  "publicai": publicaiProvider,
  "puter": puterProvider,
  "qianfan": qianfanProvider,
  "qiniu": qiniuProvider,
  "qoder": qoderProvider,
  "qwen": qwenProvider,
  "qwen-web": qwen_webProvider,
  "reka": rekaProvider,
  "requesty": requestyProvider,
  "sambanova": sambanovaProvider,
  "scaleway": scalewayProvider,
  "sensenova": sensenovaProvider,
  "siliconflow": siliconflowProvider,
  "snowflake": snowflakeProvider,
  "sparkdesk": sparkdeskProvider,
  "stepfun": stepfunProvider,
  "sumopod": sumopodProvider,
  "suno": sunoProvider,
  "synthetic": syntheticProvider,
  "t3-web": t3_webProvider,
  "tencent": tencentProvider,
  "theoldllm": theoldllmProvider,
  "together": togetherProvider,
  "tokenrouter": tokenrouterProvider,
  "trae": traeProvider,
  "udio": udioProvider,
  "uncloseai": uncloseaiProvider,
  "upstage": upstageProvider,
  "v0-vercel": v0_vercelProvider,
  "venice": veniceProvider,
  "veoaifree-web": veoaifree_webProvider,
  "vercel-ai-gateway": vercel_ai_gatewayProvider,
  "vertex": vertexProvider,
  "vertex-partner": vertex_partnerProvider,
  "volcengine": volcengineProvider,
  "wafer": waferProvider,
  "wandb": wandbProvider,
  "windsurf": windsurfProvider,
  "x5lab": x5labProvider,
  "xai": xaiProvider,
  "xiaomi-mimo": xiaomi_mimoProvider,
  "yi": yiProvider,
  "yuanbao-web": yuanbao_webProvider,
  "zai": zaiProvider,
  "zed-hosted": zed_hostedProvider,
  "zenmux": zenmuxProvider,
  "zenmux-free": zenmux_freeProvider,
};
